# golangci-lint configuration for debswarm
# Run with: golangci-lint run

version: "2"

run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  # Start with defaults (errcheck, govet, ineffassign, staticcheck, unused)
  default: standard
  enable:
    - misspell      # Finds misspelled words
    - unconvert     # Removes unnecessary type conversions
    - unparam       # Reports unused function parameters
    - nakedret      # Finds naked returns in large functions
    - prealloc      # Suggests preallocations
    - nilerr        # Finds code returning nil after checking error
    - bodyclose     # Checks HTTP response body is closed
    - noctx         # Finds HTTP requests without context
    - rowserrcheck  # Checks sql.Rows.Err is checked
    - sqlclosecheck # Checks sql.Rows and sql.Stmt are closed

  settings:
    errcheck:
      check-type-assertions: false
      check-blank: false
      exclude-functions:
        - (*os.File).Close
        - (io.Closer).Close
        - (*database/sql.Rows).Close
        - (*database/sql.Stmt).Close
        - (*database/sql.Tx).Rollback
        - (net/http.ResponseWriter).Write
        - io.Copy

    govet:
      disable:
        - fieldalignment

    nakedret:
      max-func-lines: 30

    misspell:
      locale: US

  exclusions:
    rules:
      - path: _test\.go
        linters:
          - errcheck
          - unparam
          - nakedret
          - govet
          - rowserrcheck
          - noctx

      - linters:
          - unparam
        text: "always receives"

      - path: benchmark
        linters:
          - errcheck

      # TODO: Add context to SQL calls in cache and downloader packages
      # These use internal DB operations where context cancellation isn't critical
      # See: https://github.com/debswarm/debswarm/issues/XXX
      - path: internal/cache/cache\.go
        linters:
          - noctx

      - path: internal/downloader/state\.go
        linters:
          - noctx

formatters:
  enable:
    - gofmt         # Checks code formatting
    - goimports     # Checks import ordering

issues:
  max-issues-per-linter: 50
  max-same-issues: 3
